The following works as a review for myself into Linear Algebra and Python. I have more experience with R than python, but the two are fairly similar. Later entries will be more involved.

Finding Eigen values and vectors using built in functions

In [ ]:
from scipy import linalg
import numpy as np

a = np.eye(3) *5
b = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    b[i,j] = (i+1)*(j+1)
print('a=\n',a,'\n\n','b=\n',b)

eigval, eigvec, = np.linalg.eig(a)
print('\n\n','eigenvalue of a=\n',eigval,'\n\n','eigenvector of a=\n',eigvec)

eigval, eigvec, = np.linalg.eig(b)
print('\n\n','eigenvalue of b=\n',eigval,'\n\n','eigenvector of b=\n',eigvec)

a=
 [[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]] 

 b=
 [[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


 eigenvalue of a=
 [5. 5. 5.] 

 eigenvector of a=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 eigenvalue of b=
 [ 1.40000000e+01  2.58591657e-16 -5.28378741e-16] 

 eigenvector of b=
 [[ 0.26726124 -0.10729925  0.80696533]
 [ 0.53452248 -0.81036844 -0.57890429]
 [ 0.80178373  0.57601204  0.11694775]]


Finding determinant of a matrix

In [ ]:
print('b=\n',b, '\n\n', 'determinant of b=\n',np.linalg.det(b) ) #using b again from ealier

b=
 [[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]] 

 determinant of b=
 0.0


Lets see if pythons built in function can solve this matrix

In [ ]:
k = [[1],[2],[3]]
try:
  ans = np.linalg.solve(b,k)
  print(ans)
except Exception as e:
  print(e)

Singular matrix


The built in functions fails if you give it a singular matrix, definetely good to know for the future. Lets try solving it again with a non-singular matrix

In [ ]:
d = [ [1,0,-2], [-1,1,4], [2,1,2] ]
print('d=\n',d,'\n\ndeterminant of d=',np.linalg.det(d),'\n\n')

try:
  d_ans = np.linalg.solve(d,k) #using k from before
  print(d_ans)
except Exception as e:
  print(e)

d=
 [[1, 0, -2], [-1, 1, 4], [2, 1, 2]] 

determinant of d= 4.0 


[[ 0. ]
 [ 4. ]
 [-0.5]]
